//! Node kind `write_note`.

use crate::error::{NexusError, Result};
use crate::flow::engine::{single, NodeCtx, Outputs};
use crate::registry::nodes::{NodeKind, NodeRegistry};
use crate::agent::tools;
use crate::flow::engine::render_value;
use serde_json::json;

pub fn register(r: &mut NodeRegistry) {
    r.add(NodeKind {
        id: "write_note",
        label: "Write Note",
        description: "Write the `content` input into a new note under notes/.",
        cacheable: true,
        run,
    });
}

/// `write_note`: input `content` → a new note (knowledge generated by the flow).
fn run(ctx: &NodeCtx) -> Result<Outputs> {
    let content = ctx.inputs.get("content").map(render_value).ok_or_else(|| NexusError::invalid("write_note: input `content` is not connected"))?;
    let title = ctx.cfg_str("title").unwrap_or_else(|| format!("{} output", ctx.loaded.flow.meta.name));
    let dir = ctx.cfg_str("dir").unwrap_or_else(|| "notes/generated".into());
    let path = tools::write_generated_note(ctx.tools, &dir, &title, &content)?;
    ctx.note(format!("wrote [[{}]]", path.trim_end_matches(".md")));
    Ok(single(ctx.out_port(), json!({ "path": path, "title": title })))
}
