//! Build script: Tauri codegen + node-kind discovery.
//!
//! Every `src/nodes/*.rs` file is a node kind exposing
//! `pub fn register(r: &mut NodeRegistry)`. This script generates the module
//! list, so adding a node type is one new file — no edit to core code.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let dir = Path::new("src/nodes");
    println!("cargo:rerun-if-changed=src/nodes");
    let mut files: Vec<String> = std::fs::read_dir(dir)
        .map(|rd| {
            rd.flatten()
                .filter_map(|e| {
                    let name = e.file_name().to_string_lossy().into_owned();
                    let stem = name.strip_suffix(".rs")?.to_owned();
                    (stem != "mod" && stem.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')).then_some(stem)
                })
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    let abs = std::fs::canonicalize(dir).expect("src/nodes exists");
    let mut out = String::from("// @generated by build.rs from src/nodes/*.rs — do not edit.\n");
    for f in &files {
        let path = abs.join(format!("{f}.rs"));
        // Debug formatting escapes backslashes in Windows paths.
        writeln!(out, "#[path = {:?}]\npub mod {f};", path.to_string_lossy()).unwrap();
    }
    out.push_str("\npub fn register_all(r: &mut crate::registry::nodes::NodeRegistry) {\n");
    for f in &files {
        writeln!(out, "    {f}::register(r);").unwrap();
    }
    out.push_str("}\n");
    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("node_kinds.rs");
    std::fs::write(dest, out).unwrap();

    tauri_build::build()
}
