//! Built-in node executors.

use super::engine::{render, render_value, NodeCtx, Outputs};
use crate::agent::tools::{self, Tool};
use crate::error::{NexusError, Result};
use crate::index::{query, sql};
use serde_json::{json, Map, Value};

const MAX_DOCS: usize = 200;
const MAX_DOC_CHARS: usize = 12_000;

fn one(port: String, v: Value) -> Outputs {
    let mut m = Map::new();
    m.insert(port, v);
    m
}

/// `fetch`: notes matching `config.source` (a path or SQLite GLOB) → documents.
pub fn fetch(ctx: &NodeCtx) -> Result<Outputs> {
    let source = ctx.cfg_str("source").ok_or_else(|| NexusError::invalid("fetch: config.source is required"))?;
    let source = crate::fs::normalize_rel(&source);
    let paths: Vec<String> = if source.contains(['*', '?', '[']) {
        ctx.vault.index.flush()?;
        let c = ctx.vault.index.read()?;
        let mut stmt = c.prepare_cached("SELECT path FROM files WHERE path GLOB ?1 AND kind NOT IN ('attachment', 'canvas') ORDER BY path LIMIT ?2")?;
        let rows = stmt.query_map(rusqlite::params![source, MAX_DOCS as i64], |r| r.get(0))?;
        rows.collect::<rusqlite::Result<_>>()?
    } else {
        vec![source.clone()]
    };
    let mut docs = Vec::with_capacity(paths.len());
    for p in &paths {
        let text = ctx.vault.read_text(p)?;
        let (fm, body) = crate::index::parser::split_frontmatter(&text);
        let fm = fm.and_then(|y| crate::index::parser::parse_frontmatter(y).ok()).unwrap_or_default();
        let title = fm.get("title").and_then(Value::as_str).map(str::to_owned).unwrap_or_else(|| p.rsplit('/').next().unwrap_or(p).trim_end_matches(".md").to_owned());
        docs.push(json!({ "path": p, "title": title, "content": body.trim().chars().take(MAX_DOC_CHARS).collect::<String>(), "frontmatter": fm }));
    }
    ctx.note(format!("fetched {} document(s) from `{source}`", docs.len()));
    Ok(one(ctx.out_port(), Value::Array(docs)))
}

/// `agent`: render the template prompt with inputs, run the LLM with the
/// template's allowed tools.
pub fn agent(ctx: &NodeCtx) -> Result<Outputs> {
    let cfg = ctx.vault.config();
    let model = ctx.cfg_str("model").or_else(|| ctx.template.meta.model.clone()).unwrap_or_else(|| cfg.llm.model.clone());
    let provider = crate::agent::provider_for(&cfg.llm)?;
    let mut prompt = render(&ctx.template.body, ctx);
    // Inputs the template didn't reference still reach the model.
    for (k, v) in ctx.inputs {
        if !ctx.template.body.contains(&format!("{{{{{k}}}}}")) {
            prompt.push_str(&format!("\n\n# Input `{k}`\n\n{}", render_value(v)));
        }
    }
    let system = ctx.cfg_str("system").unwrap_or_else(|| {
        "You are an agent inside Nexus, a Markdown knowledge base. Use the tools to read and query notes when helpful. \
         Reply with the requested output only."
            .into()
    });
    let all = tools::builtin();
    let allowed: Vec<&dyn Tool> = all
        .iter()
        .map(|t| t.as_ref())
        .filter(|t| ctx.template.meta.tools.iter().any(|n| *n == t.spec().name))
        .collect();
    ctx.note(format!("provider `{}`, model `{model}`, tools [{}]", provider.id(), allowed.iter().map(|t| t.spec().name).collect::<Vec<_>>().join(", ")));
    let out = crate::agent::run(provider.as_ref(), &model, &system, &prompt, &allowed, ctx.tools, cfg.llm.max_tool_steps)?;
    for t in &out.tools {
        ctx.note(format!("tool `{}` {} {}", t.name, t.arguments, if t.ok { "→ ok" } else { "→ error" }));
    }
    ctx.note(format!("{} step(s)", out.steps));
    let port = ctx.out_port();
    let ty = ctx.template.output(&port).map(|p| p.ty);
    let value = match ty {
        Some(super::types::PortType::Json) => serde_json::from_str(&out.text).unwrap_or(Value::String(out.text)),
        _ => Value::String(out.text),
    };
    Ok(one(port, value))
}

/// `write_note`: input `content` → a new note (knowledge generated by the flow).
pub fn write_note(ctx: &NodeCtx) -> Result<Outputs> {
    let content = ctx.inputs.get("content").map(render_value).ok_or_else(|| NexusError::invalid("write_note: input `content` is not connected"))?;
    let title = ctx.cfg_str("title").unwrap_or_else(|| format!("{} output", ctx.loaded.flow.meta.name));
    let dir = ctx.cfg_str("dir").unwrap_or_else(|| "notes/generated".into());
    let path = tools::write_generated_note(ctx.tools, &dir, &title, &content)?;
    ctx.note(format!("wrote [[{}]]", path.trim_end_matches(".md")));
    Ok(one(ctx.out_port(), json!({ "path": path, "title": title })))
}

/// `git_commit`: write input `content` to `config.path`, then commit now.
pub fn git_commit(ctx: &NodeCtx) -> Result<Outputs> {
    let git = ctx.vault.git.as_ref().ok_or_else(|| NexusError::invalid("git_commit: the vault is not a git repository"))?;
    let content = ctx.inputs.get("content").map(render_value).ok_or_else(|| NexusError::invalid("git_commit: input `content` is not connected"))?;
    let path = ctx.cfg_str("path").unwrap_or_else(|| format!("notes/generated/{}.md", crate::vault::slugify(&ctx.loaded.flow.meta.name)));
    ctx.vault.write_text(&path, &content, None)?;
    let sha = git.flush()?.unwrap_or_default();
    ctx.note(format!("committed {path} {}", if sha.is_empty() { "(no changes)".to_owned() } else { sha[..8.min(sha.len())].to_owned() }));
    Ok(one(ctx.out_port(), Value::String(sha)))
}

/// `query_graph`: backlinks of `config.target`, or FTS `config.search` → note refs.
pub fn query_graph(ctx: &NodeCtx) -> Result<Outputs> {
    let c = ctx.vault.index.read()?;
    let refs: Vec<Value> = if let Some(search) = ctx.cfg_str("search") {
        drop(c);
        ctx.vault.index.flush_fts()?;
        let c = ctx.vault.index.read()?;
        query::search(&c, &search, 50).map_err(sql)?.into_iter().map(|h| json!({ "path": h.path, "title": h.title })).collect()
    } else {
        let target = ctx.cfg_str("target").ok_or_else(|| NexusError::invalid("query_graph: set config.target or config.search"))?;
        let path = query::resolve(&c, &target).map_err(sql)?.ok_or_else(|| NexusError::NotFound(target.clone()))?;
        query::backlinks(&c, &path).map_err(sql)?.into_iter().map(|b| json!({ "path": b.path, "title": b.title })).collect()
    };
    ctx.note(format!("{} note(s)", refs.len()));
    Ok(one(ctx.out_port(), Value::Array(refs)))
}
